# Generated by Django 4.1.1 on 2022-09-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_pause',
            new_name='guest_can_pause',
        ),
    ]
